In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_rows",None)

In [3]:
lines = pd.read_csv("london.lines.csv")
stations = pd.read_csv("london.stations.csv")

# header = 1 , tells pandas to use the second row as column names
distance= pd.read_excel("Inter_station_database.xlsx",header= 1)

In [4]:
lines.columns = lines.columns.str.strip()

In [5]:
lines

    line                     name  colour  stripe
0      1            Bakerloo Line  AE6017     NaN
1      3              Circle Line  FFE02B     NaN
2      6  Hammersmith & City Line  F491A8     NaN
3      7             Jubilee Line  949699     NaN
4     11            Victoria Line  0A9CDA     NaN
5      2             Central Line  F15B2E     NaN
6      4            District Line  00A166     NaN
7      5         East London Line  FBAE34     NaN
8      8        Metropolitan Line  91005A     NaN
9      9            Northern Line  000000     NaN
10    10          Piccadilly Line  094FA3     NaN
11    12     Waterloo & City Line  88D0C4     NaN
12    13  Docklands Light Railway  00A77E  FFFFFF

In [6]:
lines["name"].value_counts()

name
Bakerloo Line              1
Circle Line                1
Hammersmith & City Line    1
Jubilee Line               1
Victoria Line              1
Central Line               1
District Line              1
East London Line           1
Metropolitan Line          1
Northern Line              1
Piccadilly Line            1
Waterloo & City Line       1
Docklands Light Railway    1
Name: count, dtype: int64

In [7]:
lines["name"] = lines["name"].str.strip()

In [8]:
lines.drop(columns = ["stripe"],inplace = True)

In [9]:
# Removing the unwanted lines
lines = lines[(lines["name"] != "East London Line") &  (lines["name"] != "Docklands Light Railway")]

In [10]:
lines["name"].value_counts()

name
Bakerloo Line              1
Circle Line                1
Hammersmith & City Line    1
Jubilee Line               1
Victoria Line              1
Central Line               1
District Line              1
Metropolitan Line          1
Northern Line              1
Piccadilly Line            1
Waterloo & City Line       1
Name: count, dtype: int64

In [11]:
# Removing "Line" at the end to make it consisntent with the other dataset
lines["name"] = lines["name"].str.replace("Line", "").str.strip()

In [12]:
lines["name"].value_counts()

name
Bakerloo              1
Circle                1
Hammersmith & City    1
Jubilee               1
Victoria              1
Central               1
District              1
Metropolitan          1
Northern              1
Piccadilly            1
Waterloo & City       1
Name: count, dtype: int64

In [13]:
stations.head()

,id,latitude,longitude,name,display_name,zone,total_lines,rail
0,1,51.5028,-0.2801,Acton Town,Acton<br />Town,3.0,2,0
1,2,51.5143,-0.0755,Aldgate,NaN,1.0,2,0
2,3,51.5154,-0.0726,Aldgate East,Aldgate<br />East,1.0,2,0
3,4,51.5107,-0.0130,All Saints,All<br />Saints,2.0,1,0
4,5,51.5407,-0.2997,Alperton,NaN,4.0,1,0

In [14]:
stations = stations.drop(columns = ["display_name"])

In [15]:
len(set(stations["name"]))

302

In [16]:
stations["name"].value_counts()

name
Acton Town                     1
Aldgate                        1
Aldgate East                   1
All Saints                     1
Alperton                       1
Angel                          1
Archway                        1
Arnos Grove                    1
Arsenal                        1
Baker Street                   1
Balham                         1
Bank                           1
Barbican                       1
Barking                        1
Barkingside                    1
Barons Court                   1
Bayswater                      1
Beckton                        1
Beckton Park                   1
Becontree                      1
Belsize Park                   1
Bethnal Green                  1
Blackfriars                    1
Blackhorse Road                1
Blackwall                      1
Bond Street                    1
Borough                        1
Boston Manor                   1
Bounds Green                   1
Bow Church                     1
Bow Road                       1
Brent Cross                    1
Bromley-By-Bow                 1
Burnt Oak                      1
Caledonian Road                1
Camden Town                    1
Canary Wharf                   1
Cannon Street                  1
Canons Park                    1
Chalk Farm                     1
Chancery Lane                  1
Charing Cross                  1
Chigwell                       1
Chiswick Park                  1
Clapham Common                 1
Clapham North                  1
Clapham South                  1
Colindale                      1
Colliers Wood                  1
Covent Garden                  1
Crossharbour & London Arena    1
Custom House                   1
Cyprus                         1
Dagenham East                  1
Dagenham Heathway              1
Devons Road                    1
Dollis Hill                    1
Ealing Broadway                1
Ealing Common                  1
Earl's Court                   1
Eastcote                       1
East Acton                     1
East Finchley                  1
East Ham                       1
East India                     1
East Putney                    1
Edgware                        1
Edgware Road (B)               1
Edgware Road (C)               1
Elephant & Castle              1
Elm Park                       1
Embankment                     1
Euston                         1
Euston Square                  1
Fairlop                        1
Farringdon                     1
Finchley Central               1
Finchley Road                  1
Finsbury Park                  1
Fulham Broadway                1
Gallions Reach                 1
Gants Hill                     1
Gloucester Road                1
Golders Green                  1
Goldhawk Road                  1
Goodge Street                  1
Grange Hill                    1
Great Portland Street          1
Greenford                      1
Green Park                     1
Gunnersbury                    1
Hainault                       1
Hammersmith                    1
Hampstead                      1
Hanger Lane                    1
Harlesden                      1
Harrow & Wealdston             1
Harrow-on-the-Hill             1
Hatton Cross                   1
Heathrow Terminals 1, 2 & 3    1
Heathrow Terminal 4            1
Hendon Central                 1
Heron Quays                    1
High Street Kensington         1
Highbury & Islington           1
Highgate                       1
Hillingdon                     1
Holborn                        1
Holland Park                   1
Holloway Road                  1
Hornchurch                     1
Hounslow Central               1
Hounslow East                  1
Hounslow West                  1
Hyde Park Corner               1
Ickenham                       1
Island Gardens                 1
Kennington                     1
Kensal Green                   1
Kensington (Olympia)           1
Kentish Town                   1
Kenton                         1
Kew Gardens                    1
Kilburn                        1
Kilburn Park                   1
Kingsbury                      1
King's Cross St. Pancras       1
Knightsbridge                  1
Ladbroke Grove                 1
Lambeth North                  1
Lancaster Gate                 1
Latimer Road                   1
Leicester Square               1
Leyton                         1
Leytonstone                    1
Limehouse                      1
Liverpool Street               1
London Bridge                  1
Maida Vale                     1
Manor House                    1
Mansion House                  1
Marble Arch                    1
Marylebone                     1
Mile End                       1
Mill Hill East                 1
Monument                       1
Moorgate                       1
Moor Park                      1
Morden                         1
Mornington Crescent            1
Mudchute                       1
Neasden                        1
Newbury Park                   1
Northfields                    1
Northolt                       1
Northwick Park                 1
Northwood                      1
Northwood Hills                1
North Acton                    1
North Ealing                   1
North Harrow                   1
North Wembley                  1
Notting Hill Gate              1
Old Street                     1
Osterley                       1
Oval                           1
Oxford Circus                  1
Paddington                     1
Park Royal                     1
Parsons Green                  1
Perivale                       1
Picadilly Circus               1
Pimlico                        1
Pinner                         1
Plaistow                       1
Poplar                         1
Preston Road                   1
Prince Regent                  1
Putney Bridge                  1
Queen's Park                   1
Queensbury                     1
Queensway                      1
Ravenscourt Park               1
Rayners Lane                   1
Redbridge                      1
Regent's Park                  1
Richmond                       1
Roding Valley                  1
Rotherhithe                    1
Royal Albert                   1
Royal Oak                      1
Royal Victoria                 1
Ruislip                        1
Ruislip Manor                  1
Russell Square                 1
Seven Sisters                  1
Shadwell                       1
Shepherd's Bush (C)            1
Shepherd's Bush (H)            1
Shoreditch                     1
Sloane Square                  1
Snaresbrook                    1
Southfields                    1
South Ealing                   1
South Harrow                   1
South Kensington               1
South Kenton                   1
South Quay                     1
South Ruislip                  1
South Wimbledon                1
South Woodford                 1
Stamford Brook                 1
Stanmore                       1
Stepney Green                  1
Stockwell                      1
Stonebridge Park               1
Stratford                      1
St. James's Park               1
St. John's Wood                1
St. Paul's                     1
Sudbury Hill                   1
Sudbury Town                   1
Surrey Quays                   1
Swiss Cottage                  1
Temple                         1
Tooting Bec                    1
Tooting Broadway               1
Tottenham Court Road           1
Tottenham Hale                 1
Tower Gateway                  1
Tower Hill                     1
Tufnell Park                   1
Turnham Green                  1
Turnpike Lane                  1
Upminster                      1
Upminster Bridge               1
Upney                          1
Upton Park                     1
Uxbridge                       1
Vauxhall                       1
Victoria                       1
Walthamstow Central            1
Wanstead                       1
Wapping                        1
Warren Street                  1
Warwick Avenue                 1
Waterloo                       1
Wembley Central                1
Wembley Park                   1
Westbourne Park                1
Westferry                      1
Westminster                    1
West Acton                     1
West Brompton                  1
West Finchley                  1
West Ham                       1
West Hampstead                 1
West Harrow                    1
West India Quay                1
West Kensington                1
West Ruislip                   1
Whitechapel                    1
White City                     1
Willesden Green                1
Willesden Junction             1
Wimbledon                      1
Wimbledon Park                 1
Woodford                       1
Woodside Park                  1
Wood Green                     1
Brixton                        1
Amersham                       1
Bermondsey                     1
Chesham                        1
Chalfont & Latimer             1
Chorleywood                    1
Rickmansworth                  1
Croxley                        1
Watford                        1
Ruislip Gardens                1
High Barnet                    1
Totteridge & Whetstone         1
Cockfosters                    1
Oakwood                        1
Southgate                      1
Epping                         1
Theydon Bois                   1
Debden                         1
Loughton                       1
Buckhurst Hill                 1
Pudding Mill Lane              1
Southwark                      1
Canada Water                   1
Canning Town                   1
North Greenwich                1
Cutty Sark                     1
Greenwich                      1
Deptford Bridge                1
Elverson Road                  1
Lewisham                       1
New Cross                      1
New Cross Gate                 1
Name: count, dtype: int64

In [17]:
distance.head()

,Line,Direction,Station from (A),Station to (B),Distance (Kms),Un-impeded Running Time (Mins),AM peak (0700-1000) Running Time (Mins),Inter peak (1000 - 1600) Running time (mins)
0,Bakerloo,Southbound,HARROW & WEALDSTONE,KENTON,1.74,2.233333,2.500000,2.500000
1,Bakerloo,Southbound,KENTON,SOUTH KENTON,1.40,1.883333,2.000000,2.000000
2,Bakerloo,Southbound,SOUTH KENTON,NORTH WEMBLEY,0.90,1.500000,1.500000,1.500000
3,Bakerloo,Southbound,NORTH WEMBLEY,WEMBLEY CENTRAL,1.27,1.916667,2.058824,2.058824
4,Bakerloo,Southbound,WEMBLEY CENTRAL,STONEBRIDGE PARK,1.71,2.233333,3.125000,3.125000

In [18]:
distance["Line"].value_counts()

Line
District           118
Northern           102
Piccadilly         102
Central             98
Circle              72
Metropolitan        70
H & C               56
Jubilee             52
Bakerloo            48
Victoria            30
East London         16
Waterloo & City      2
Name: count, dtype: int64

In [19]:
#Removing the unwanted lines that do not exist anymore
distance = distance[distance["Line"] != "East London"]

In [20]:
distance["Line"].value_counts()

Line
District           118
Northern           102
Piccadilly         102
Central             98
Circle              72
Metropolitan        70
H & C               56
Jubilee             52
Bakerloo            48
Victoria            30
East London         16
Waterloo & City      2
Name: count, dtype: int64

In [21]:
# change the Line name to be consistent with the other dataset
distance.loc[distance["Line"] == "H & C", "Line"] = "Hammersmith & City"

In [22]:
distance["Line"] = distance["Line"].str.replace("Line","").str.strip()

In [23]:
all_stations = set(distance["Station from (A)"]) | set(distance["Station to (B)"])

In [24]:
len(all_stations)

289

In [25]:
distance.drop(columns = ["Un-impeded Running Time (Mins)"] , inplace = True)
distance.drop(columns = ["AM peak (0700-1000) Running Time (Mins)","Inter peak (1000 - 1600) Running time (mins)"], inplace = True)

In [26]:
distance["Station from (A)"] = distance["Station from (A)"].str.lower()
distance["Station to (B)"] = distance["Station to (B)"].str.lower()
stations["name"] = stations["name"].str.lower()

In [27]:
distance["Line"].value_counts()

Line
District              118
Northern              102
Piccadilly            102
Central                98
Circle                 72
Metropolitan           70
Hammersmith & City     56
Jubilee                52
Bakerloo               48
Victoria               30
East London            16
Waterloo & City         2
Name: count, dtype: int64

In [28]:
distance.to_csv(r"C:\Users\MR.CO\Desktop\London Uderground\Cleaned_datasets\distance_c.csv", index = False)
stations.to_csv(r"C:\Users\MR.CO\Desktop\London Uderground\Cleaned_datasets\stations_c.csv", index = False)
lines.to_csv(r"C:\Users\MR.CO\Desktop\London Uderground\Cleaned_datasets\lines_c.csv", index = False)